Prow workloads control plane
kubevirt/project-infra pull request #1025
Opened 2021-03-11 18:42 UTC by fgimenez

Adds kubespray code to deploy the prow-workloads cluster control plane. Also includes a prow job to trigger it. The ssh key, inventory and vars files required by kubespray will come from the secrets file, this PR puts them in place https://github.com/kubevirt/secrets/pull/15

/cc @dhiller @rmohr

2021-03-15 16:51 UTC, dhiller approved these changes
/approve
/hold

need to wait for the secrets PR to get merged.

2021-03-15 16:56 UTC, dhiller commented on github/ci/prow-workloads/hack/deploy.sh
> +        extract_secret 'prowWorkloads.ssKey' ~/.ssh/id_ed25519
```suggestion
        extract_secret 'prowWorkloads.sshKey' ~/.ssh/id_ed25519
```

2021-03-15 16:57 UTC, dhiller requested changes
/lgtm cancel 

one secret key is wrong, see comment.

2021-03-15 16:59 UTC, dhiller commented
/hold cancel

Other PR for secrets is merged

2021-03-15 17:08 UTC, fgimenez commented
> one secret key is wrong, see comment.

great catch, thanks a lot! :)

2021-03-16 08:58 UTC, dhiller approved these changes

2021-03-16 08:59 UTC, merged