kubemacpool, Add lanes for new stable branch release-v0.21
kubevirt/project-infra pull request #1206
Opened 2021-05-09 12:11 UTC by RamLavi

This PR Adds lanes for new stable branch release-v0.21

2021-05-09 12:12 UTC, RamLavi commented
/rehearse

2021-05-10 07:44 UTC, qinqon requested changes

2021-05-10 07:44 UTC, qinqon commented on github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
> +        fork-per-release: "true"
This is not needed

2021-05-10 07:44 UTC, qinqon commented on github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
> +        fork-per-release: "true"
ditto

2021-05-10 11:06 UTC, RamLavi commented on github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
> +        fork-per-release: "true"
Done

2021-05-10 11:06 UTC, RamLavi commented on github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
> +        fork-per-release: "true"
Done

2021-05-10 11:11 UTC, qinqon commented
/lgtm
/approve

2021-05-10 11:22 UTC, merged