Add presubmit linting jobs for kubevirt-github-io
kubevirt/project-infra pull request #1545
Opened 2021-09-04 04:20 UTC by tylerauerbeck

Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>

@mazzystr Took an initial run at https://github.com/kubevirt/kubevirt.github.io/issues/785

This (I _think_) will add presubmit jobs to begin linting markdown files and running spell checks (in addition to the existing link checker). Please let me know if this is the appropriate place or if there is somewhere else this belongs.

2021-09-07 17:51 UTC, mazzystr commented
/ok-to-test

2021-09-07 17:53 UTC, mazzystr commented
OMG we're linting the website.  Everyone run and seek shelter!  ;-)

I'm very interested to see the results here.  Thanks for this submission @tylerauerbeck !

2021-09-08 01:26 UTC, tylerauerbeck commented
@mazzystr Looks like the current issue was just a misnamed job. 🤞🏻 Hopefully that fixes things up.

2021-09-08 02:35 UTC, mazzystr requested changes

2021-09-08 02:35 UTC, mazzystr commented on github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
> +    - name: kubevirt-io-presubmit-spell-checker
Ooof!  I didn't notice this...  Could you separate this to a different pull req?

2021-09-08 02:40 UTC, mazzystr commented
@tylerauerbeck ...
kubevirt-io-presubmit-spell-checker is going to need to be moved to it's own pull req.  Sorry that I missed it earlier.

re kubevirt-io-presubmit-markdown-linter ... I ran `make check_lint` just to see where we stand.  It looks like we have 20 errors on `kubevirt.github.io:~/_posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md`.  If you can fix those issues we can approve this job.

2021-09-09 19:08 UTC, mazzystr commented
@tylerauerbeck Thanks for that adjustment.   Now we need an update to [./_posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md](https://github.com/kubevirt/kubevirt.github.io/blob/master/_posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md) so we don't cause other contributors to get distracted by other errors.

Sorry to put you through the wringer on this.  This pull req really is looking great.

2021-09-10 03:55 UTC, tylerauerbeck commented
@mazzystr No problems at all. Opened https://github.com/kubevirt/kubevirt.github.io/pull/796 to deal with the listing issues. Once that one is merged, we should be good to go!

2021-09-14 21:37 UTC, tylerauerbeck commented
@mazzystr Looks like #796 was merged. So this looks good to go now?

2021-09-21 21:22 UTC, mazzystr commented
@tylerauerbeck Here we go!

/lgtm
/approve

2021-09-21 21:32 UTC, merged