macvtap: Use podman on postsubmit jobs
kubevirt/project-infra pull request #2285
Opened 2022-08-24 10:28 UTC by oshoval

Signed-off-by: Or Shoval <oshoval@redhat.com>

2022-08-24 10:29 UTC, oshoval commented
@brianmcarey 
Is there a way to test postsubmit before merging it ? (not sure there is)

2022-08-24 10:29 UTC, oshoval commented
/rehearse

2022-08-24 10:47 UTC, brianmcarey commented
> @brianmcarey Is there a way to test postsubmit before merging it ? (not sure there is, unless running manual on CI or so)

There isn't really as far as I know. . The hope would be that the majority actions in a postsubmit job would be covered by presubmits in the repo so if the update works in the presubmits - it should work in the postsubmit. 

@dhiller is there a method of testing postsubmits that I am missing?

2022-08-25 10:21 UTC, brianmcarey reviewed
/lgtm

2022-08-25 12:24 UTC, oshoval commented
/cc @phoracek can you take a look please ?

2022-08-25 12:35 UTC, oshoval commented
Hi @maiqueb 
can you take a look please as well ?

2022-08-25 13:08 UTC, maiqueb requested changes

2022-08-25 13:11 UTC, oshoval commented on github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
> +              value: podman
We run at `automation/release.sh`, this command `make release`
release depends on `release: docker-build docker-push`, which depends on `OCI_BIN`
```
docker-build:
	$(OCI_BIN) build -t ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -f ./cmd/Dockerfile .
```

2022-08-25 13:18 UTC, maiqueb commented on github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
> +              value: podman
Oh. You're right ... while the release make target does [**not** require](https://github.com/kubevirt/macvtap-cni/blob/main/hack/release.sh) the `OCI_BIN` variable, its dependencies [do](https://github.com/kubevirt/macvtap-cni/blob/c40e78241abd048d322952b93ed42d80ea258979/Makefile#L125).

2022-08-25 13:20 UTC, maiqueb approved these changes
I stand corrected. 

@phoracek I wonder if it makes sense to have the release make target depend on img building / img generation: it releases the src code ... as long as it builds (and the tests pass ...) we should be able to release the src code, right ?

2022-08-29 11:31 UTC, phoracek commented
/approve

2022-08-29 11:32 UTC, phoracek commented
@maiqueb you mean to make sure we test before we push the images to public? That makes sense

2022-08-29 11:37 UTC, maiqueb commented
> @maiqueb you mean to make sure we test before we push the images to public? That makes sense

I unfortunately don't have room to take any task right now. I agree it makes sense, I just can't make up room for this.

2022-08-29 11:38 UTC, maiqueb commented
> > @maiqueb you mean to make sure we test before we push the images to public? That makes sense
> 
> I unfortunately don't have room to take any task right now. I agree it makes sense, I just can't make up room for this.

Furthermore, what would the "test" look like ? I am practically illiterate on this repo.

2022-08-29 13:18 UTC, oshoval commented
/retest-required

2022-08-29 16:15 UTC, merged