Use the new unified web container image for user-guide
kubevirt/project-infra pull request #2460
Opened 2022-11-14 19:15 UTC by cwilkers

Should fix https://github.com/kubevirt/user-guide/issues/623

Signed-off-by: cwilkers <cwilkers@redhat.com>

2022-11-14 19:16 UTC, cwilkers commented
CC @dhiller

2022-11-17 07:11 UTC, dhiller requested changes
@cwilkers thank you for this!

I think you need to correct one image reference to point to quay, other than that looks good to me!

2022-11-17 07:11 UTC, dhiller commented on github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
> +      - image: kubevirt-kubevirt.github.io:v20220825-9d7149f
```suggestion
      - image: quay.io/kubevirtci/kubevirt-kubevirt.github.io:v20220825-9d7149f
```

2022-11-17 17:05 UTC, dhiller approved these changes
/approve

2022-11-17 17:06 UTC, merged