external plugins: Introduce specify plugin
kubevirt/project-infra pull request #3164
Opened 2024-01-11 11:23 UTC by oshoval

2024-03-10 10:58 UTC, oshoval commented
> @oshoval: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-prow-kubevirt-labels-update-precheck	[cb31120](https://github.com/kubevirt/project-infra/commit/cb31120865eb0c24ec785ae12798a9f5583e2923)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3164/pull-prow-kubevirt-labels-update-precheck/1766074452900057088)	true	`/test pull-prow-kubevirt-labels-update-precheck`
> pull-prow-nmstate-labels-update-precheck	[cb31120](https://github.com/kubevirt/project-infra/commit/cb31120865eb0c24ec785ae12798a9f5583e2923)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3164/pull-prow-nmstate-labels-update-precheck/1766074452979748864)	true	`/test pull-prow-nmstate-labels-update-precheck`

how come it runs it on draft

2024-04-07 11:52 UTC, oshoval commented
/close

lets reopen once / if we are back to it

2025-02-03 14:38 UTC, oshoval commented
https://github.com/kubevirt/project-infra/compare/main...oshoval:project-infra:specify
already started here at the past (not tested, still need work of course)

2025-02-03 14:45 UTC, dhiller commented
/cc

2025-02-13 11:16 UTC, oshoval commented
resolved conflicts only

2025-02-16 12:34 UTC, oshoval commented
@brianmcarey @dhiller 
before i rename it (anyhow it is still wip),
do you like the name Daniel suggest `test-subset` ? 

btw, maybe better to consider a name without `-` ?
easier to trigger it, and maybe looks bit nicer on the manifests (but this is nit)

2025-03-03 14:08 UTC, dhiller commented
> @brianmcarey @dhiller before i rename it (anyhow it is still wip), do you like the name Daniel suggest `test-subset` ?
> 
> btw, maybe better to consider a name without `-` ? easier to trigger it, and maybe looks bit nicer on the manifests (but this is nit)

IMHO the dash should stay for readability reasons, also it seems common practice to use it as can be seen on our command help page: https://prow.ci.kubevirt.io/command-help

2025-03-03 15:15 UTC, oshoval commented
renamed

2025-03-04 08:22 UTC, oshoval commented
@dhiller @brianmcarey 
basically ready for review please
once review is done, will need to push the image and update the manifest, and if we can deploy it on prow please
meanwhile will compare the manifests to the phased one to see nothing is missing

thanks

2025-03-04 08:43 UTC, oshoval commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +            secretName: oauth-token
atm the plugin doesn't comment, if we add comments or in case required we will need to change to `commenter-oauth-token` (according comparison to phased plugin)

2025-03-04 16:08 UTC, dhiller requested changes
@oshoval I just got to review it quickly, I'll do another review tomorrow.

2025-03-05 08:24 UTC, oshoval commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +          image: quay.io/kubevirtci/test-subset:v20240108-87253b59
it is old indeed, once we review we need to rebuild and update the manifest please
it is just a place holder for now

i think we can do it in the same pr, once the code is lgtmed, but up to you
i tested only with unit test, so would help please to test it on real env or such if possible please
(as done with phased plugin, with the help of Brian, and went good)

2025-03-05 08:26 UTC, oshoval commented on external-plugins/test-subset/plugin/handler/handler.go
> +	org, repo := OrgRepo(pr.Base.Repo.FullName)
btw here i implemented the [OrgRepo](https://github.com/kubevirt/project-infra/pull/3164/files#diff-8383ef4cc8ae969cfad9de54ad4822aefef45adc934082855cc975a25d057d24R357) because the old functioned with that name doesn't exists
so i assume pr.Base.Repo.FullName does equal "kubevirt/kubevirt"

2025-03-05 09:10 UTC, oshoval commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +      app: prow-test-subset
here to keep preifx prow ?
(otoh on line 4 and 6 it is without)

2025-03-05 09:11 UTC, oshoval commented
Thanks, addressed comments

2025-03-05 13:04 UTC, dhiller commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +          image: quay.io/kubevirtci/test-subset:v20240108-87253b59
IIRC I've been using [Phony](https://docs.prow.k8s.io/docs/components/cli-tools/phony/) for this

2025-03-05 13:05 UTC, dhiller commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +      app: prow-test-subset
IMHO remove it also here

2025-03-05 13:14 UTC, oshoval commented on github/ci/prow-deploy/kustom/base/manifests/local/prow-test-subset-deployment.yaml
> +          image: quay.io/kubevirtci/test-subset:v20240108-87253b59
for that i already have the unit tests and it works
i dont think it will give additional benefit, and it won't worth the time of that
i will be glad please if we can test it on the real cluster, it ain't risky, and will save lot of time

2025-03-05 13:47 UTC, dhiller reviewed
Looks good already, some nits and one question inside.

2025-03-05 13:54 UTC, oshoval commented on external-plugins/test-subset/plugin/handler/handler.go
> +	job := pjutil.NewPresubmit(*pr, pr.Base.SHA, presubmit, event.GUID, map[string]string{})
not sure, but i think it does the needed stuff about it (by modifiers according the comment here)
https://go-mod-viewer.appspot.com/sigs.k8s.io/prow@v0.0.0-20241021132706-9efd512d94f7/pkg/pjutil/pjutil.go
i think we can just try and see :)

2025-03-05 14:03 UTC, oshoval commented
thanks, addressed comments
(had to rename a manifest due to removing the `prow-` prefix)

2025-03-17 08:22 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +	org, repo := OrgRepo(pr.Base.Repo.FullName)
Not sure, do you mean this one? https://github.com/kubevirt/project-infra/blob/0c50140b09af8beffb92c27f8f9319f33f851af3/robots/pkg/github/events.go#L28

2025-03-17 08:23 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +	org, repo := OrgRepo(pr.Base.Repo.FullName)
admitttedly a bit hidden in the events.go file

2025-03-17 08:25 UTC, oshoval commented on external-plugins/test-subset/plugin/handler/handler.go
> +	org, repo := OrgRepo(pr.Base.Repo.FullName)
thanks, seems so yep i can try to use that
ps.
https://github.com/kubevirt/project-infra/blob/0c50140b09af8beffb92c27f8f9319f33f851af3/robots/pkg/github/events.go#L30
aint it a bug ? i.e we first need to assert length of the split array and then access it, else it can panic

2025-03-17 08:35 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +	org, repo := OrgRepo(pr.Base.Repo.FullName)
yeah would be safer if that was done first, agree

2025-03-17 10:04 UTC, dhiller requested changes
@oshoval looks great already, I have left two comments inline.

2025-03-17 10:04 UTC, dhiller commented on external-plugins/test-subset/plugin/main.go
> +		Description: `The Test-subset plugin is used to trigger a job that run custom subset of the tests`,
since the prow instance will display the help [here](https://prow.ci.kubevirt.io/plugins) and [here](https://prow.ci.kubevirt.io/command-help#test), and this one is similar to the `trigger` plugin we should structure the help content similar, i.e. at least tell users looking at the plugin docs how to use it and what command(s) are available.

See trigger plugin helpProvider as example here: https://github.com/kubernetes-sigs/prow/blob/a3626d1e12d61ca2c560a6a6ff12d310c101a319/pkg/plugins/trigger/trigger.go#L83

Note: you needn't aim to be as comprehensive but at least the bar minimum should be provided.

![image](https://github.com/user-attachments/assets/03822747-9b70-44ae-bde6-f30bb4606298)

2025-03-17 11:41 UTC, oshoval commented
rebased only

2025-03-17 11:48 UTC, oshoval commented
```
11:42:41: 2025-03-17T11:42:41.203474Z	info	failed to download quay.io/kubevirtci/k8s-1.33:2503141050-fe4dac80: Error response from daemon: {"progressDetail":{},"errorDetail":{"message":"initializing source docker://quay.io/kubevirtci/k8s-1.33:2503141050-fe4dac80: reading manifest 2503141050-fe4dac80 in quay.io/kubevirtci/k8s-1.33: unauthorized: access to the requested resource is not authorized"},"error":"initializing source docker://quay.io/kubevirtci/k8s-1.33:2503141050-fe4dac80: reading manifest 2503141050-fe4dac80 in quay.io/kubevirtci/k8s-1.33: unauthorized: access to the requested resource is not authorized"}
11:42:41: panic: Failed to download cluster image quay.io/kubevirtci/k8s-1.33:2503141050-fe4dac80, failed to download quay.io/kubevirtci/k8s-1.33:2503141050-fe4dac80 four times, giving up.
```

@brianmcarey fyi please
need to make public it seems

2025-03-17 11:53 UTC, oshoval commented on external-plugins/test-subset/plugin/main.go
> +		Description: `The Test-subset plugin is used to trigger a job that run custom subset of the tests`,
as example i guess you meant this link
https://github.com/kubernetes-sigs/prow/blob/a3626d1e12d61ca2c560a6a6ff12d310c101a319/pkg/plugins/trigger/trigger.go#L106

thanks

2025-03-17 13:50 UTC, oshoval commented
/retest

2025-03-17 14:34 UTC, dhiller requested changes
@oshoval nearly there, found only two things, commented inline.

2025-03-17 14:34 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +var LoadConfigBytesFunc loadConfigBytesFunc = loadConfigBytes
you have the SetLocal... func, so this variable doesn't need the be exported.

2025-03-17 14:34 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +}
Please use structured logging:

```suggestion
	log.SetFormatter(&logrus.JSONFormatter{})
}
```

2025-03-17 15:33 UTC, oshoval commented
addressed comments, ptal

2025-03-17 16:13 UTC, dhiller commented on external-plugins/test-subset/plugin/handler/handler.go
> +var LoadConfigBytesFunc loadConfigBytesFunc = loadConfigBytes
I am just saying that the variable doesn't need to be exported because you are setting the default already on init(), where for unit tests you call the SetLocal func, so it can be changed to 
```suggestion
var loadConfigBytesFunc loadConfigBytesFunc = loadConfigBytes
```
as it need not be assignable from outside the package - unless I am missing something.
(I figure you need to change the type name ofcourse)

2025-03-18 09:04 UTC, oshoval commented on external-plugins/test-subset/plugin/handler/handler.go
> +var LoadConfigBytesFunc loadConfigBytesFunc = loadConfigBytes
ah right, thanks done

2025-03-18 09:04 UTC, oshoval commented
addressed comments, ptal
thanks

2025-03-18 09:34 UTC, dhiller approved these changes
/approve

Thank you @oshoval !

2025-03-18 09:35 UTC, merged

2025-03-18 09:42 UTC, oshoval commented
general note - we might want to consider running the `make test` (maybe also the `make build`) of the plugins on CI jobs, they are short and this way once someone adds new plugin it will be tested

2025-08-14 13:12 UTC, oshoval commented
still wip, but with those 2, using focus / verbosity should work from chat-op
it basically turns chat-op to shell like command, allowing to parse it with native pflag

https://github.com/kubevirt/project-infra/pull/4312
https://github.com/kubevirt/kubevirt/pull/15445