HCO: Add tests for the new release-1.11 branch
kubevirt/project-infra pull request #3201
Opened 2024-01-22 10:11 UTC by dharmit

2024-01-22 10:12 UTC, dharmit commented
I have used k8s v1.27 & 1.28 instead of 1.26 & 1.27 in previous PRs. PTAL if something needs to be changed.

/cc @nunnatsa 
/cc @tiraboschi

2024-01-23 12:39 UTC, nunnatsa commented
/ok-to-test

2024-01-23 12:47 UTC, nunnatsa requested changes
Thanks for the PR @dharmit 

Please find some inline comments.

2024-01-23 12:47 UTC, nunnatsa commented on github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.11.yaml
> +  - name: pull-hyperconverged-cluster-operator-e2e-k8s-1.27-centos9
Please remove the `-centos9` suffix. This is not needed and confusing.

2024-01-23 12:47 UTC, nunnatsa commented on github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.11.yaml
> +      - image: quay.io/kubevirtci/golang:v20230626-e1b7af2
maybe we can use something newer?

2024-01-23 12:47 UTC, nunnatsa commented on github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.11.yaml
> +      - image: quay.io/kubevirtci/golang:v20230626-e1b7af2
same

2024-01-23 12:47 UTC, nunnatsa commented on github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.11.yaml
> +        - "export TARGET=k8s-1.27-centos9 && automation/test.sh"
there is no `k8s-1.27-centos9`. please change to `k8s-1.27`

2024-01-24 13:06 UTC, nunnatsa commented
/rehearse

2024-01-24 14:24 UTC, nunnatsa commented
/lgtm
/approve

2024-01-24 16:44 UTC, merged