Release configs for kubevirt/kubevirt release branch release-1.4
kubevirt/project-infra pull request #3707
Opened 2024-10-23 06:38 UTC by xpivarc

adds new release configs

2024-10-23 14:12 UTC, xpivarc commented
/cc @dhiller @brianmcarey

2024-10-24 10:05 UTC, dhiller requested changes
@xpivarc the jobs for 1.29 and 1.30 in this config need to get switched to `always_run: true` - you can find these by looking at jobs in the main config that have `run_before_merge: true`

2024-10-30 12:50 UTC, brianmcarey commented
@xpivarc @dhiller - I think we need to get this merged in case anyone creates a backport to 1.4.

2024-11-04 08:44 UTC, brianmcarey reviewed
Thanks @xpivarc  - just a couple of comments inline

2024-11-04 09:03 UTC, xpivarc commented on github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
> +    optional: true
I am not sure about that, do we require root anywhere?

2024-11-04 09:06 UTC, brianmcarey commented on github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
> +    optional: true
Sorry you are right - early morning

2024-11-04 09:08 UTC, xpivarc commented on github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
> +  - always_run: false
This is root and I am not sure if it is required

2024-11-04 12:46 UTC, dhiller reviewed
/approve

/hold to wait for cache drop

2024-11-04 12:50 UTC, dhiller commented
> /approve
> 
> /hold to wait for cache drop

Hmm, I am still not seeing the expected change from `always_run: false` to  `always_run: true`, as also @brianmcarey pointed out.

2024-11-05 07:49 UTC, dhiller approved these changes

2024-11-05 08:29 UTC, brianmcarey reviewed
/lgtm

/hold cancel

2024-11-05 08:30 UTC, merged