labels: Rename topic/network to sig/network
kubevirt/project-infra pull request #580
Opened 2020-08-12 13:34 UTC by EdDev

The label plugin supports labeling using a command only specific types
and "topic" is not one of them.

"sig" is a supported type and is equivalent in meaning to the "topic"
one.
With this change, one can label a PR or issue using the
`/sig network` comment.

2020-08-12 13:34 UTC, EdDev commented
/cc @phoracek

2020-08-12 13:58 UTC, phoracek commented
/lgtm

But I'd like to hear from somebody who understands Prow config better, to make sure we don't break anything.

2020-08-13 05:30 UTC, EdDev commented
/cc @danielBelenky

2020-08-20 09:05 UTC, danielBelenky requested changes
For the sake of consistency, let's either change the label for everyone or keep it as `topic/network`.
I personally don't have any preference on that... just want things to be consistent.

2020-08-20 09:11 UTC, EdDev commented
> For the sake of consistency, let's either change the label for everyone or keep it as `topic/network`.
> I personally don't have any preference on that... just want things to be consistent.

I think each team can only control their own labels and I cannot enforce this on all. I especially do not think I can remove the old ones for the others.
If it is just adding, I am fine with adding the others as well.

2020-08-20 09:32 UTC, danielBelenky commented
> > For the sake of consistency, let's either change the label for everyone or keep it as `topic/network`.
> > I personally don't have any preference on that... just want things to be consistent.
> 
> I think each team can only control their own labels and I cannot enforce this on all. I especially do not think I can remove the old ones for the others.
> If it is just adding, I am fine with adding the others as well.

I'm all for aligning our verticals with how K8s defines them (SIGs).
Let's raise it on the mailing list. I just don't want to have confusing labels on PRs and issues.

2020-08-26 07:07 UTC, rmohr commented
/lgtm
/approve

2020-08-26 07:08 UTC, merged

2020-08-26 07:10 UTC, rmohr commented
Labels are synchronized twice a day. It will take a few hours until the changes are effective.