SRIOV lane: Mount in memory directory for backing in-memory etcd data
kubevirt/project-infra pull request #709
Opened 2020-11-15 19:28 UTC by ormergi

Currently we encounter bad performance of KIND
cluster on DinD setup, we get 'etcdserver: timeout errors'
that causes jobs to fail often.

In such cases it is recommended to run in-memory 
etcd https://github.com/kubernetes-sigs/kind/issues/845 
https://github.com/kubernetes-sigs/kind/issues/1922
Running etcd in memory should improve performance and
make sriov lane more stabilized

2020-11-15 19:29 UTC, ormergi commented
/cc @qinqon @EdDev @dhiller @danielBelenky

2020-11-16 08:50 UTC, qinqon requested changes

2020-11-16 08:50 UTC, qinqon commented on github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
> +          - name: etcd-data
This is `etcd-data-dir`

2020-11-16 08:54 UTC, oshoval reviewed
In my opinion, a retry or other solutions ad hoc, would be better until we have faster HD (SSD), because ramfs might be too sterile 
and mask problems / opportunities (and we can see the latest changes as example)

2020-11-16 09:57 UTC, ormergi commented on github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
> +          - name: etcd-data
Fixed

2020-11-16 10:07 UTC, ormergi commented
/reharse pull-kubevirt-e2e-k8s-1.17-sriov

2020-11-16 10:18 UTC, ormergi commented
/rehearse pull-kubevirt-e2e-k8s-1.17-sriov

2020-11-16 10:28 UTC, ormergi commented
/rehearse pull-kubevirt-e2e-kind-1.17-sriov

2020-11-16 10:47 UTC, ormergi commented
/rehearse check-up-kind-1.17-sriov

2020-11-16 10:48 UTC, ormergi commented
/rehearse check-up-kind-1.17-sriov

2020-11-16 10:52 UTC, ormergi commented
/rehearse check-up-kind-1.17-sriov

2020-11-16 12:47 UTC, danielBelenky commented
/rehearse

2020-11-17 08:32 UTC, ormergi commented
/rehearse

2020-11-17 08:32 UTC, ormergi commented
/rehearse

2020-11-17 08:36 UTC, ormergi commented
/rehearse

2020-11-17 08:41 UTC, ormergi commented
/rehearse

2020-11-17 08:56 UTC, ormergi commented
/cc @EdDev cancel

2020-11-17 09:06 UTC, ormergi commented
/uncc @EdDev @oshoval @qinqon @omeryahud @dhiller @danielBelenky @cynepco3hahue 

Not ready for review yet

2020-11-17 09:08 UTC, ormergi commented
/unassign @qinqon @oshoval

2020-11-17 09:09 UTC, ormergi commented
/uncc @oshoval @qinqon

2020-11-17 09:10 UTC, ormergi commented
/rehearse

2020-11-17 09:11 UTC, ormergi commented
/rehearse

2020-11-17 09:16 UTC, ormergi commented
/rehearse

2020-11-17 11:10 UTC, ormergi commented
The mount is created
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/709/rehearsal-check-up-kind-1.17-sriov/1328628056557883392#1:build-log.txt%3A95

2020-11-17 11:13 UTC, ormergi commented
/rehearse

2020-11-17 11:27 UTC, ormergi commented
/rehearse

2020-11-17 11:36 UTC, ormergi commented
/rehearse

2020-11-17 11:55 UTC, ormergi commented
The mount is created and functional for kubevirtci check-up job
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/709/rehearsal-check-up-kind-1.17-sriov/1328663414439940097

2020-11-17 11:59 UTC, qinqon commented
/rehearse pull-kubevirt-e2e-kind-1.17-sriov

2020-11-17 12:40 UTC, ormergi commented
/rehearse

2020-11-17 12:42 UTC, ormergi commented
/rehearse

2020-11-17 12:49 UTC, ormergi commented
/rehearse

2020-11-17 14:02 UTC, ormergi commented
/rehearse

2020-11-17 14:03 UTC, ormergi commented
/rehearse pull-kubevirt-e2e-kind-1.17-sriov

2020-11-17 14:28 UTC, ormergi commented
/rehearse

2020-11-17 14:53 UTC, ormergi commented
/rehearse

2020-11-17 14:55 UTC, ormergi commented
/rehearse

2020-11-17 16:25 UTC, ormergi commented
@qinqon 
Running check up job with kubevirt/kubevirtci#478 on top using rehearsal plugin.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/709/rehearsal-check-up-kind-1.17-sriov/1328713493427261440

This jobs running kubevirt tests with kubevirt/kubevirtci#478 on top using rehearsal plugin
It means that running tests using etcd in memory works. 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/709/rehearsal-pull-kubevirt-e2e-kind-1.17-sriov/1328713493427261441

2020-11-17 16:36 UTC, ormergi commented
/rehearse

2020-11-18 06:48 UTC, ormergi commented
/rehearse

2020-11-18 07:34 UTC, ormergi commented
pull kubevirt e2e job passed with kubevirt/kubevirtci#478 changes on cluster-up
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/709/rehearsal-pull-kubevirt-e2e-kind-1.17-sriov/1328953198081216512

2020-11-18 08:28 UTC, qinqon commented
/hold
This is a testing PR rigth now, it has to be cleaned up to be merged.

2020-11-18 08:43 UTC, ormergi commented
> /hold
> This is a testing PR rigth now, it has to be cleaned up to be merged.

Done 
I also added another commit to ensure cluster teardown to prevent resource leaks

2020-11-20 11:24 UTC, ormergi commented
Rebased

2020-11-22 10:18 UTC, ormergi commented
/hold

Looks like we wont need it

2020-11-23 13:44 UTC, ormergi commented
/close

No need to create a mount for etcd data anymore

2020-11-23 13:44 UTC, closed without merging