Add a knmstate lane for future nmstate version
kubevirt/project-infra pull request #765
Opened 2020-12-04 11:51 UTC by qinqon

Signed-off-by: Quique Llorente <ellorent@redhat.com>

2020-12-04 11:56 UTC, qinqon commented
/cc @phoracek @rhrazdil

2020-12-04 11:57 UTC, qinqon commented
/uncc @oshoval @RamLavi

2020-12-10 10:31 UTC, rhrazdil requested changes

2020-12-10 10:31 UTC, rhrazdil commented on github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
> +
nit: extra newline

2020-12-11 06:24 UTC, qinqon commented
/rehearse

2020-12-11 08:30 UTC, phoracek commented
/lgtm
/approve

2020-12-11 08:32 UTC, phoracek commented
/overried  rehearsal-pull-kubernetes-nmstate-e2e-handler-k8s-future

2020-12-11 08:32 UTC, phoracek commented
/override rehearsal-pull-kubernetes-nmstate-e2e-handler-k8s-future

2020-12-11 08:32 UTC, merged