Release configs for kubevirt/kubevirt release branch release-0.37
kubevirt/project-infra pull request #805
Opened 2021-01-04 18:45 UTC by davidvossel

adds new release configs

2021-01-12 16:14 UTC, rmohr commented
/hold

This does not seem to take the new config-forker into account which should generate unique names.

2021-01-19 11:28 UTC, rmohr commented
/retest

2021-01-20 09:21 UTC, rmohr commented
/hold cancel

2021-01-20 12:15 UTC, oshoval requested changes

2021-01-20 12:15 UTC, oshoval commented on github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
> +            topologyKey: kubernetes.io/hostname
can you please add 
```
            - labelSelector:
                matchExpressions:
                  - key: sriov-pod-multi
                    operator: In
                    values:
                      - "true"
              topologyKey: kubernetes.io/hostname
```
as https://github.com/kubevirt/project-infra/pull/843 introduced?
It will allow to run the multi sriov POC in parallel to the official jobs

This PR was generated manually or with some help tools ? 
(in case its with tools, i will update them if needed)

Thanks

2021-01-20 12:18 UTC, rmohr commented on github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
> +            topologyKey: kubernetes.io/hostname
This PR gets generated when the release branch is cut and just takes the master configuration at this time.

2021-01-20 12:18 UTC, rmohr commented
/lgtm
/approve

2021-01-20 12:18 UTC, rmohr commented on github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
> +            topologyKey: kubernetes.io/hostname
can you backport this please after this PR if you need it?

2021-01-20 12:20 UTC, oshoval commented on github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
> +            topologyKey: kubernetes.io/hostname
sure thanks, will add it

btw, it means that in case the job is generated when the release is out, but then the master config is changed, we lose the changes (as this what happened now i think, since master config has it)

2021-01-20 12:35 UTC, rmohr commented on github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
> +            topologyKey: kubernetes.io/hostname
> btw, it means that in case the job is generated when the release is out, but then the master config is changed, we lose the changes (as this what happened now i think, since master config has it)

Yes this is intentional. This ensures that old release branches continue working while new jobs can evolve without having to think about backward compatibility. Changes like yours, which you want to propagate back are very seldom compared to doing forward-looking-only changes.

2021-01-20 12:38 UTC, rmohr commented
/hold

I am still not convinced that we will not see the statusreconciler regression. Checking now.

2021-01-20 14:37 UTC, rmohr commented
/close

replaced with #872

2021-01-20 14:37 UTC, closed without merging