sriov cni, Fix NetworkAttachmentDefinition missing namespace
kubevirt/project-infra pull request #823
Opened 2021-01-10 11:51 UTC by oshoval

Add missing namespace for the CNI NetworkAttachmentDefinition.
Prow jobs expect the CNI to be in the same namespace of multus daemon set.
In the CI we saw that the namespace of the SRIOV CNI is indeed at
multus daemonset multus-cni-ns.

Signed-off-by: Or Shoval <oshoval@redhat.com>

2021-01-10 11:52 UTC, oshoval commented on cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
>      {
maybe need also the change next line to 0.3.1 as the cni binary itself outputs 0.3.1

2021-01-10 11:53 UTC, oshoval commented
/cc @EdDev

2021-01-19 13:13 UTC, EdDev requested changes
The change itself seems fine to me, but the commit itself is very confusing.
The terms are intermixed and it is hard to follow.

Please also make it clear that the correct namespace is applied in production and is just not present in the sources. The commit sentence that tries to express that is not clear.

2021-01-19 15:19 UTC, oshoval commented
Addressed comments

2021-01-20 08:19 UTC, EdDev approved these changes

2021-01-20 08:20 UTC, oshoval commented
Thanks Edy

2021-01-20 08:44 UTC, oshoval commented
/cc @qinqon 
Can you please take a look ?

2021-01-20 10:34 UTC, qinqon commented
/lgtm
/approve

2021-01-20 10:36 UTC, merged

2021-01-20 10:49 UTC, oshoval commented
Thanks Quique.