WIP: Periodically Check for a new Fedora version and create a new CDI
kubevirt/project-infra pull request #871
Opened 2021-01-20 13:51 UTC by shwetaap

Periodically Check for a new Fedora version and create a new Containerdiskimage for it in the registry

Signed-off-by: Shweta Padubidri <spadubid@redhat.com>

2021-01-21 07:25 UTC, rmohr commented
/cc @fgimenez 

If there are no annotations on the job, shoulld the testgrid-config pick this job up?

2021-01-21 09:01 UTC, fgimenez requested changes

2021-01-21 09:01 UTC, fgimenez commented on github/ci/prow/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
> +  decorate: true
```suggestion
  annotations:
    testgrid-create-test-group: "false" 
  decorate: true
```

2021-01-21 09:04 UTC, fgimenez commented
> If there are no annotations on the job, shoulld the testgrid-config pick this job up?

Good catch, periodics should either define the dashboard to which the job should be added or declare that we don't want it to be shown.  I've proposed a small change to not include this job in testgrid, it should fix https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/871/pull-project-infra-check-testgrid-config/1352042776916660225 too.

2021-01-28 16:21 UTC, fgimenez approved these changes
/lgtm

2021-01-28 16:38 UTC, rmohr commented
/approve

the job is not ready. Appriving to allow @shwetaap iterating on it.

2021-01-28 17:02 UTC, merged